app = "ai-backend-service"
primary_region = "ord"

[build]
dockerfile = "docker/Dockerfile"

[env]
DEBUG = "false"
PORT = "8000"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true

[[services]]
internal_port = 8000
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "5s"

[[services.http_checks]]
interval = "30s"
timeout = "2s"
grace_period = "5s"
method = "get"
path = "/api/v1/health/live"

[deploy]
release_command = "python -c 'print(\"Deployment ready\")'"

[[statics]]
guest_path = "/app/static"
url_prefix = "/static/"